[package]
name = "nutrition_rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "nutrition"
path = "src/main.rs"

[[bin]]
name = "nutrition-lsp"
path = "src/lsp/server.rs"

[lib]
name = "nutrition_rs"
path = "src/lib.rs"

[dependencies]
async-openai = {version = "0.32.3", features = ["chat-completion"]}
async-trait = "0.1.89"
axum = "0.8.8"
chumsky = "0.12.0"
clap = { version = "4.5.54", features = ["derive", "env"] }
logos = "0.16.0"
lsp-server = "0.7.9"
lsp-types = "0.97.0"
schemars = "1.2.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features= ["macros", "rt-multi-thread"]}
tree-sitter = "0.26.3"
tree-sitter-nutrition = { path = "tree-sitter" }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "test-util"] }
tower = "0.4"
