[package]
name = "nutrition_rs"
version = "0.1.3"
edition = "2024"
license = "MIT"
repository = "https://github.com/jafayer/nutrition-rs"
description = "A CLI for flexible plaintext nutrition tracking"
homepage = "https://github.com/jafayer/nutrition-rs"

[[bin]]
name = "nutrition"
path = "src/main.rs"
required-features = ["runtime"]

[lib]
name = "nutrition_rs"
path = "src/lib.rs"

[features]
default = ["runtime"]
runtime = ["dep:tokio", "dep:axum", "dep:async-openai", "dep:async-trait", "dep:minijinja", "dep:tower-http"]

[dependencies]
async-openai = { version = "0.32.3", features = ["chat-completion"], optional = true }
async-trait = { version = "0.1.89", optional = true }
ariadne = "0.4"
axum = { version = "0.8.8", optional = true }
tower-http = { version = "0.5", features = ["fs"], optional = true }
chumsky = "0.12.0"
clap = { version = "4.5.54", features = ["derive", "env"] }
logos = "0.16.0"
schemars = "1.2.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
minijinja = { version = "2", optional = true, features = ["loader", "builtins"] }
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"], optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "test-util"] }
tower = "0.4"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
